const TEEN={id:"azizbek",name:"Azizbek",age:15,grade:"9-sinf",profile:{logic:85,problem:88,technology:90,practical:75,creativity:65,communication:55,teamwork:60,medicine:30,organization:70,independence:80,design:70},answers:{q1:"Texnika va kompyuterlar",q2:"Matematika",q3:"Muammoni bosqichma-bosqich tahlil qilaman",q4:"Yangi texnologiyalarni sinab ko‘rish",q5:"Kompyuterda dastur yoki loyiha yaratish",q6:"Amaliy ishni ham yoqtiraman",q7:"Mustaqil ishlash qulayroq",q8:"Qiyin bo‘lsa ham qiziq bo‘lsa davom etaman",q9:"Qurilma qanday ishlashini bilishga qiziqaman",q10:"Biror narsani tuzatib ko‘raman",q11:"Matematika va informatika",q12:"Texnik masalalarni yechish",q13:"Yangi narsani o‘rganish",q14:"Ba’zan o‘zim, ba’zan jamoa bilan",q15:"Reja tuzib ishlayman",q16:"Chizma va texnik loyihalarga qiziqaman",q17:"Mexanizm va qurilmalar qiziq",q18:"Hayvonlar va tabiatga qiziqishim o‘rtacha",q19:"Odamlar bilan ko‘p gaplashish talab qilinmaydigan ish",q20:"Kompyuter yoki laboratoriya kabi muhit",q21:"Bir xil ish tez zeriktiradi",q22:"Mashaqqatli vazifani tugatishga harakat qilaman",q23:"Yangi g‘oya o‘ylab topishni yoqtiraman",q24:"Faqat yuqori maoshga qarab tanlamayman",q25:"Do‘stlarimning fikri qarorimni to‘liq belgilamaydi",q26:"Ota-onamning fikrini eshitaman, lekin o‘zim ham tahlil qilaman",q27:"O‘zimning kuchli tomonlarimni aniqlashga harakat qilaman",q28:"Kasb haqida ma’lumot va talablarni tekshiraman",q29:"Texnologiya bilan ishlash",q30:"Qiziqishim va qobiliyatimga mos kasb"}};


/* Virtual students: each has a different hidden profile and decision context. */
const STUDENTS=[
  TEEN,
  {
    id:"madina",name:"Madina",age:15,grade:"9-sinf",
    style:"Ijodkor, dizayn va muloqotga qiziqadi.",
    profile:{logic:65,problem:60,technology:70,practical:55,creativity:94,communication:86,teamwork:82,medicine:35,organization:72,independence:68,design:92},
    answerByCategory:{
      interest:"Rasm chizish, dizayn va yangi g‘oyalar bilan ishlashni yoqtiraman.",
      subject:"Adabiyot va san’atga oid fanlar ko‘proq qiziq.",
      problem:"Avval turli yechimlarni o‘ylab, eng ijodiy variantni tanlayman.",
      technology:"Yangi dastur va dizayn vositalarini sinab ko‘rishga qiziqaman.",
      career:"Dizayn va ijod bilan bog‘liq loyiha yaratishni xohlayman.",
      practical:"Qo‘l bilan nimadir yaratish yoqadi, lekin ijodiy tomoni bo‘lsa yanada yaxshi.",
      independence:"G‘oyamni mustaqil ishlab chiqish menga qulay.",
      persistence:"Yoqtirgan loyiham bo‘lsa, qiyin bo‘lsa ham davom ettiraman.",
      technical:"Texnikaning ishlashidan ko‘ra, undan qanday ijodiy foydalanish qiziq.",
      teamwork:"Jamoada fikr almashish va g‘oyalarni birlashtirishni yoqtiraman.",
      organization:"Vazifani rejalashtiraman, lekin jarayonda yangi g‘oyalar qo‘shaman.",
      design:"Rang, shakl va kompozitsiyaga e’tibor beraman.",
      medicine:"Biologiya qiziq, ammo tibbiyot asosiy qiziqishim emas.",
      communication:"Odamlar bilan fikr almashish menga yoqadi.",
      environment:"Ijodiy studiya yoki zamonaviy kompyuterli muhit qulay.",
      variety:"Bir xil ish tez zeriktiradi, yangi loyihalar yoqadi.",
      creativity:"Yangi g‘oya topish men uchun juda qiziq.",
      error_salary:"Kasbni faqat maoshiga qarab tanlash to‘g‘ri emas deb o‘ylayman.",
      error_peer:"Do‘stlarimning fikrini eshitaman, lekin tanlovimni o‘zim qilaman.",
      error_parent:"Ota-onamning maslahatini eshitaman, ammo o‘z qiziqishimni ham hisobga olaman.",
      selfknowledge:"Ijodkorligim va muloqotdagi kuchli tomonlarimni bilaman.",
      information:"Kasb talablari va ish namunalarini ko‘rib chiqaman.",
      motivation:"Men uchun qiziqish, ijod va o‘z fikrimni ifodalash muhim."
    }
  },
  {
    id:"javohir",name:"Javohir",age:16,grade:"10-sinf",
    style:"Matematika, tahlil va biznes jarayonlariga qiziqadi.",
    profile:{logic:94,problem:88,technology:72,practical:48,creativity:68,communication:70,teamwork:66,medicine:25,organization:92,independence:78,design:50},
    answerByCategory:{
      interest:"Hisob-kitob, tahlil va murakkab masalalarni yechishni yoqtiraman.",
      subject:"Matematika va iqtisodga yaqin mavzular menga qiziq.",
      problem:"Muammoni qismlarga ajratib, raqamlar va faktlar asosida yechaman.",
      technology:"Texnologiya foydali, ayniqsa ma’lumotlarni tahlil qilishda.",
      career:"Iqtisod, moliya yoki tahlil bilan bog‘liq ishni tasavvur qilaman.",
      practical:"Ko‘proq aqliy va tahliliy ishlarni afzal ko‘raman.",
      independence:"Mustaqil hisoblab, keyin natijani boshqalar bilan muhokama qilish qulay.",
      persistence:"Masala qiyin bo‘lsa, yechim topmaguncha urinaman.",
      technical:"Qurilmaning texnik tomoniga qiziqishim o‘rtacha.",
      teamwork:"Jamoada vazifalarni taqsimlab ishlash mumkin.",
      organization:"Reja, jadval va muddatlarga amal qilishni yaxshi ko‘raman.",
      design:"Chizma emas, jadval va grafiklar menga ko‘proq qiziq.",
      medicine:"Tibbiyotga qiziqishim kuchli emas.",
      communication:"Kerakli natijani tushuntirish uchun odamlar bilan gaplashaman.",
      environment:"Ofis, kompyuter va ma’lumotlar bilan ishlash muhiti qulay.",
      variety:"Tahliliy vazifalar turlicha bo‘lsa yaxshi.",
      creativity:"Yechim topishda yangi usul o‘ylab ko‘rishni yoqtiraman.",
      error_salary:"Maosh muhim, lekin kasbning menga mosligini ham tekshiraman.",
      error_peer:"Do‘stlarimning tanlovi mening qarorimni belgilamaydi.",
      error_parent:"Ota-onam maslahat beradi, lekin qarorni dalillar bilan o‘zim qilaman.",
      selfknowledge:"Tahlil va tartibga moyilligim kuchli ekanini bilaman.",
      information:"Kasbning vazifalari, daromadi va talablarini solishtiraman.",
      motivation:"Men uchun rivojlanish, natija va barqarorlik muhim."
    }
  },
  {
    id:"sevinch",name:"Sevinch",age:16,grade:"10-sinf",
    style:"Biologiya, tibbiyot va odamlarga yordam berishga qiziqadi.",
    profile:{logic:74,problem:78,technology:50,practical:70,creativity:62,communication:88,teamwork:90,medicine:95,organization:84,independence:55,design:40},
    answerByCategory:{
      interest:"Biologiya va odamlarga yordam berish bilan bog‘liq ishlar yoqadi.",
      subject:"Biologiya va kimyo fanlariga qiziqaman.",
      problem:"Muammoni tushunib, odamga xavfsiz yordam berish yo‘lini izlayman.",
      technology:"Tibbiy texnologiyalar qiziq, lekin inson bilan ishlash muhimroq.",
      career:"Tibbiyot va sog‘liqni saqlash sohasini tasavvur qilaman.",
      practical:"Amaliy mashg‘ulotlarda faol bo‘lishni yoqtiraman.",
      independence:"Ba’zi vazifalarni mustaqil, murakkablarini jamoa bilan bajaraman.",
      persistence:"Odamga yordam berish kerak bo‘lsa, qiyinchilikka qaramay davom etaman.",
      technical:"Tibbiy asboblarning ishlashini o‘rganishga qiziqaman.",
      teamwork:"Jamoa bilan ishlash men uchun juda muhim.",
      organization:"Vazifalarni tartib bilan bajarishga harakat qilaman.",
      design:"Dizaynga qiziqishim ikkinchi darajada.",
      medicine:"Tibbiyotga qiziqishim juda yuqori.",
      communication:"Odamni tinglash va tushuntirishni yaxshi ko‘raman.",
      environment:"Klinika, laboratoriya yoki tibbiy muhit menga mos.",
      variety:"Turli bemorlar va vaziyatlar ishni qiziqarli qiladi.",
      creativity:"Muammoning yangi yechimini topishga harakat qilaman.",
      error_salary:"Faqat maosh uchun kasb tanlamayman.",
      error_peer:"Do‘stlarimning kasbi emas, o‘z qiziqishim muhim.",
      error_parent:"Ota-onamning maslahatini qadrlayman, lekin o‘z qobiliyatimni ham tekshiraman.",
      selfknowledge:"Odamlar bilan ishlash va sabrli bo‘lish kuchli tomonlarim.",
      information:"Kasb talablari, o‘qish muddati va mas’uliyatini tekshiraman.",
      motivation:"Odamlarga foyda keltirish mening asosiy motivim."
    }
  },
  {
    id:"diyor",name:"Diyor",age:15,grade:"9-sinf",
    style:"Mexanika, amaliy ish va texnikaga qiziqadi.",
    profile:{logic:82,problem:84,technology:86,practical:94,creativity:70,communication:52,teamwork:62,medicine:20,organization:74,independence:76,design:72},
    answerByCategory:{
      interest:"Mashina, mexanizm va amaliy ishlar bilan shug‘ullanish yoqadi.",
      subject:"Fizika va matematika menga qiziq.",
      problem:"Muammoni ko‘rib, sababini topib amalda tekshiraman.",
      technology:"Yangi texnika va asboblarni o‘rganishga qiziqaman.",
      career:"Muhandislik, mexanika yoki texnologiya sohasini tasavvur qilaman.",
      practical:"Qo‘l bilan ishlash va biror narsa yasash menga juda yoqadi.",
      independence:"Vazifani o‘zim bajarib ko‘rishni afzal ko‘raman.",
      persistence:"Buzilgan yoki qiyin narsani tuzatmaguncha urinaman.",
      technical:"Mexanizm va qurilmalarning ichki tuzilishi qiziq.",
      teamwork:"Kerak bo‘lsa jamoa bilan ham ishlayman.",
      organization:"Asboblar va ish bosqichlarini oldindan tayyorlayman.",
      design:"Texnik chizma va konstruksiyalarga qiziqaman.",
      medicine:"Tibbiyotga qiziqishim kam.",
      communication:"Ko‘p gapirishdan ko‘ra amaliy ish menga qulay.",
      environment:"Ustaxona, laboratoriya yoki texnik muhit yoqadi.",
      variety:"Turli loyihalar bilan ishlashni yoqtiraman.",
      creativity:"Yangi qurilma yoki yechim o‘ylab topish yoqadi.",
      error_salary:"Maosh muhim, lekin kasbning o‘zimga mosligini ham tekshiraman.",
      error_peer:"Do‘stim tanlagan kasbni faqat u tanlagani uchun olmayman.",
      error_parent:"Ota-onamning fikrini eshitaman, lekin amaliy qobiliyatimni hisobga olaman.",
      selfknowledge:"Amaliy va texnik ishlar kuchli tomonim ekanini bilaman.",
      information:"Kasb uchun qanday bilim va amaliy ko‘nikma kerakligini tekshiraman.",
      motivation:"Biror narsani yaratish va ishlayotganini ko‘rish meni qiziqtiradi."
    }
  },
  {
    id:"zuhra",name:"Zuhra",age:15,grade:"9-sinf",
    style:"Til, muloqot va tashkilotchilikka moyil.",
    profile:{logic:72,problem:70,technology:55,practical:42,creativity:78,communication:96,teamwork:92,medicine:35,organization:94,independence:62,design:60},
    answerByCategory:{
      interest:"O‘qish, suhbatlashish, tadbirlar va odamlar bilan ishlashni yoqtiraman.",
      subject:"Ona tili, adabiyot va tarix qiziq.",
      problem:"Avval tomonlarni tinglab, keyin muammoni tartib bilan hal qilaman.",
      technology:"Texnologiyadan muloqot va tashkilotchilikni yengillashtirish uchun foydalanaman.",
      career:"O‘qituvchilik, huquq yoki tashkilotchilikka yaqin kasblarni tasavvur qilaman.",
      practical:"Amaliy ish bo‘lsa ham, odamlar bilan bog‘liq bo‘lishini xohlayman.",
      independence:"Mustaqil fikr bildiraman, lekin jamoa bilan maslahatlashishni yaxshi ko‘raman.",
      persistence:"Odamlar ishonib topshirgan vazifani oxirigacha bajaraman.",
      technical:"Texnik qurilmalar unchalik qiziqtirmaydi.",
      teamwork:"Jamoa bilan ishlash men uchun juda qulay.",
      organization:"Reja va tadbirlarni tashkil qilishni yaxshi ko‘raman.",
      design:"Taqdimot va tadbir bezagiga qiziqaman.",
      medicine:"Tibbiyotga qiziqishim o‘rtacha.",
      communication:"Odamlar bilan muloqot qilish kuchli tomonim.",
      environment:"Maktab, ofis yoki odamlar ko‘p bo‘lgan muhit qulay.",
      variety:"Turli odamlar va vazifalar bo‘lsa, ish qiziqarli bo‘ladi.",
      creativity:"Nutq, tadbir yoki loyiha uchun yangi g‘oyalar topaman.",
      error_salary:"Kasbni faqat daromadiga qarab tanlashni istamayman.",
      error_peer:"Do‘stlarim maslahat berishi mumkin, lekin tanlovimni o‘zim qilaman.",
      error_parent:"Ota-onamning fikrini hurmat qilaman, o‘z qiziqishimni ham asoslayman.",
      selfknowledge:"Muloqot va tashkilotchilik kuchli tomonlarim.",
      information:"Kasbning vazifalari va talablarini oldindan o‘rganaman.",
      motivation:"Odamlar bilan ishlash va foydali bo‘lish meni rag‘batlantiradi."
    }
  }
];

const STUDENT_QUESTION_POOLS={"azizbek":["q3","q4","q9","q10","q11","q12","q15","q17","q21","q22","q28","q31","q41","q42","q49","q51","q52","q61","q67","q92"],"madina":["q1","q4","q16","q23","q35","q43","q45","q46","q54","q55","q62","q63","q65","q72","q86","q89","q98","q100"],"javohir":["q2","q3","q11","q13","q15","q28","q32","q38","q39","q47","q57","q60","q66","q70","q78","q88","q94","q95","q97"],"sevinch":["q2","q12","q18","q36","q37","q45","q56","q64","q65","q71","q72","q81","q83","q90","q91","q95","q97","q100"],"diyor":["q6","q9","q10","q16","q17","q41","q42","q49","q51","q52","q61","q68","q69","q87","q92","q93","q94","q99"],"zuhra":["q12","q14","q19","q25","q26","q32","q36","q37","q44","q45","q58","q59","q65","q72","q75","q79","q84","q85","q97","q98"]};

const getStudentAnswer=(student,q)=>{
  return student.answers?.[q.id] || student.answerByCategory?.[q.category] || "Bu haqda hali aniq o‘ylab ko‘rmaganman.";
};

const QUESTIONS=[
{id:"q1",text:"Bo‘sh vaqtingizda nimalar bilan shug‘ullanishni ko‘proq yoqtirasiz?",answers:["Sport va faol harakat","Texnika va kompyuterlar","Odamlar bilan suhbat","Rasm, musiqa yoki ijod"],category:"interest",weight:8},
{id:"q2",text:"Maktabda qaysi fan sizga ko‘proq qiziq?",answers:["Matematika","Biologiya","Tarix","Adabiyot"],category:"subject",weight:8},
{id:"q3",text:"Murakkab muammoga duch kelsangiz, odatda nima qilasiz?",answers:["Muammoni bosqichma-bosqich tahlil qilaman","Boshqalardan darhol yordam so‘rayman","Keyinga qoldiraman","Taxminan javob beraman"],category:"problem",weight:10},
{id:"q4",text:"Yangi texnologiya paydo bo‘lsa, munosabatingiz qanday?",answers:["Qiziqib o‘rganaman","Faqat majbur bo‘lsam foydalanaman","Qiziqmayman","Boshqalardan foydalanishni o‘rganaman"],category:"technology",weight:9},
{id:"q5",text:"Qaysi faoliyat sizga yaqinroq?",answers:["Kompyuterda dastur yoki loyiha yaratish","Odamlarni davolash","O‘quvchilarga dars berish","Huquqiy masalalarni hal qilish"],category:"career",weight:10},
{id:"q6",text:"Amaliy, qo‘l bilan bajariladigan ishlar sizga qanday?",answers:["Amaliy ishni ham yoqtiraman","Umuman yoqtirmayman","Faqat majbur bo‘lsam","Faqat ijodiy ishni xohlayman"],category:"practical",weight:8},
{id:"q7",text:"Ishlash uslubidan qaysi biri sizga qulay?",answers:["Mustaqil ishlash qulayroq","Faqat jamoada ishlash","Rahbar aytganini bajarish","Farqi yo‘q"],category:"independence",weight:7},
{id:"q8",text:"Qiyin, lekin qiziqarli vazifa berilsa nima qilasiz?",answers:["Qiyin bo‘lsa ham qiziq bo‘lsa davom etaman","Tezda voz kechaman","Boshqa odamga topshiraman","Faqat oson bo‘lsa qilaman"],category:"persistence",weight:8},
{id:"q9",text:"Qurilma yoki mexanizm ko‘rsangiz, sizda qanday qiziqish uyg‘onadi?",answers:["Qanday ishlashini bilishga qiziqaman","Faqat tashqi ko‘rinishiga qarayman","Umuman qiziqmayman","Faqat narxiga qiziqaman"],category:"technical",weight:9},
{id:"q10",text:"Biror buyum buzilsa, birinchi reaksiyangiz qanday?",answers:["O‘zim tuzatib ko‘raman","Darhol ustaga beraman","Tashlab yuboraman","Boshqalardan so‘rayman"],category:"practical",weight:8},
{id:"q11",text:"Qaysi fanlar sizdagi kuchli tomonlarni ko‘proq namoyon qiladi?",answers:["Matematika va informatika","Biologiya va kimyo","Tarix va huquq","Til va adabiyot"],category:"subject",weight:9},
{id:"q12",text:"Qaysi turdagi vazifani bajarish sizga yoqadi?",answers:["Texnik masalalarni yechish","Odamlarning muammosini tinglash","Matn yozish","Tadbir tashkil qilish"],category:"problem",weight:8},
{id:"q13",text:"Kasb tanlashda siz uchun eng muhim omillardan biri nima?",answers:["Yangi narsani o‘rganish","Faqat yuqori maosh","Kasbning mashhurligi","Do‘stlarimning tanlovi"],category:"motivation",weight:8},
{id:"q14",text:"Jamoaviy topshiriqda o‘zingizni qanday tutasiz?",answers:["Ba’zan o‘zim, ba’zan jamoa bilan","Faqat yolg‘iz ishlayman","Faqat boshqaraman","Hech qachon fikr bildirmayman"],category:"teamwork",weight:6},
{id:"q15",text:"Katta vazifani bajarishda qanday yo‘l tutasiz?",answers:["Reja tuzib ishlayman","Oxirgi kungacha kutaman","Boshqalarga ergashaman","Tasodifiy boshlayman"],category:"organization",weight:7},
{id:"q16",text:"Chizma, sxema va texnik loyihalar sizga qiziqmi?",answers:["Ha, qiziq","Umuman qiziq emas","Faqat baho uchun","Bilmayman"],category:"design",weight:8},
{id:"q17",text:"Mexanizm va qurilmalar haqida o‘ylash sizga qanday ta’sir qiladi?",answers:["Qiziq tuyuladi","Zerikarli","Faqat ishlatishni bilsam bo‘ldi","E’tibor bermayman"],category:"technical",weight:8},
{id:"q18",text:"Tabiat, hayvonlar yoki biologik jarayonlar sizni qanchalik qiziqtiradi?",answers:["Juda qiziqtiradi","O‘rtacha","Kam qiziqtiradi","Umuman qiziqtirmaydi"],category:"medicine",weight:6},
{id:"q19",text:"Qaysi ish muhiti sizga ko‘proq mos?",answers:["Odamlar bilan doimiy muloqot","Kompyuter yoki laboratoriya","Doimiy safar","Sahna va ommaviy chiqish"],category:"communication",weight:7},
{id:"q20",text:"Qaysi ish muhiti sizni qulay his qildiradi?",answers:["Kompyuter yoki laboratoriya kabi muhit","Katta savdo zali","Sinf xonasi","Sud yoki rasmiy idora"],category:"environment",weight:7},
{id:"q21",text:"Bir xil ishni uzoq vaqt takrorlashga munosabatingiz qanday?",answers:["Tez zeriktiradi","Muammo emas","Faqat mukofot bo‘lsa","Boshqalarga topshiraman"],category:"variety",weight:6},
{id:"q22",text:"Mashaqqatli vazifani tugatish haqida nima deysiz?",answers:["Tugatishga harakat qilaman","Tezda voz kechaman","Boshqa odamni kutaman","Faqat oson qismini qilaman"],category:"persistence",weight:7},
{id:"q23",text:"Yangi g‘oya o‘ylab topish sizga yoqadimi?",answers:["Ha, yoqadi","Umuman yoqmaydi","Faqat tayyor namuna bilan","Ba’zan"],category:"creativity",weight:7},
{id:"q24",text:"Kasbni faqat yuqori maoshiga qarab tanlash haqida fikringiz?",answers:["Faqat maoshga qarab tanlamayman","Ha, eng muhimi maosh","Boshqalar nima desa shuni qilaman","Prestij bo‘lsa yetarli"],category:"error_salary",weight:10},
{id:"q25",text:"Do‘stlaringizning kasb tanlovingizga ta’siri qanday?",answers:["Fikrimni eshitaman, lekin qarorni o‘zim qilaman","Ular tanlaganini tanlayman","Do‘stlarim nima desa shu","Bilmayman"],category:"error_peer",weight:10},
{id:"q26",text:"Ota-onangizning kasb bo‘yicha fikri siz uchun qanday?",answers:["Eshitaman, lekin o‘zim ham tahlil qilaman","Faqat ularning xohishini bajaraman","Umuman quloq solmayman","Do‘stlarim muhimroq"],category:"error_parent",weight:10},
{id:"q27",text:"O‘zingizning kuchli va zaif tomonlaringizni bilasizmi?",answers:["Aniqlashga harakat qilaman","Bu haqda o‘ylamaganman","Hamma narsani yaxshi bilaman","Boshqalar aytishi kerak"],category:"selfknowledge",weight:10},
{id:"q28",text:"Kasb haqida qaror qilishdan oldin ma’lumotlarni qanday tekshirasiz?",answers:["Kasb haqida ma’lumot va talablarni tekshiraman","Biror odam aytsa yetarli","Faqat reklama ko‘raman","Tekshirmay tanlayman"],category:"information",weight:10},
{id:"q29",text:"Qaysi faoliyatda o‘zingizni ko‘proq tasavvur qilasiz?",answers:["Texnologiya bilan ishlash","Odamlarga tibbiy yordam berish","Odamlarni o‘qitish","Huquqiy himoya"],category:"career",weight:9},
{id:"q30",text:"Siz uchun ideal kasb qanday bo‘lishi kerak?",answers:["Qiziqishim va qobiliyatimga mos","Eng ko‘p pul beradigan","Eng mashhur kasb","Do‘stlarim havas qiladigan"],category:"motivation",weight:9}
,
{id:"q31",text:"Biror narsani o‘rganishda qaysi usul sizga qulay?",answers:["Matematika va informatika","Biologiya va kimyo","Tarix va huquq","Til va adabiyot","Fizika va texnologiya","San’at va dizayn"],category:"subject",weight:7},
{id:"q32",text:"Yangi vazifani olganingizda birinchi nima qilasiz?",answers:["Vazifalarni bosqichlarga ajrataman","Darhol ishni boshlayman","Boshqalardan yordam so‘rayman","Eng oson qismini qilaman","Muddatni hisoblayman","Vaziyatga qarab o‘zgartiraman"],category:"organization",weight:7},
{id:"q33",text:"Xatoga yo‘l qo‘ysangiz qanday yo‘l tutasiz?",answers:["Qayta urinib ko‘raman","Yordam so‘rayman","Boshqa usul sinayman","Vazifani keyinga qoldiraman","Faqat oson qismini qilaman","Natija chiqmaguncha davom etaman"],category:"persistence",weight:7},
{id:"q34",text:"O‘zingiz bilmagan mavzuga duch kelsangiz nima qilasiz?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q35",text:"Biror loyiha uchun g‘oya topishda nimaga ko‘proq e’tibor berasiz?",answers:["Bir nechta yangi variant o‘ylayman","Tayyor namunani takrorlayman","Boshqalardan g‘oya so‘rayman","Avvalgi usulni ishlataman","G‘oyani chizma qilib ko‘raman","Amalda sinab ko‘raman"],category:"creativity",weight:7},
{id:"q36",text:"Odamning muammosini eshitganingizda odatda nima qilasiz?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q37",text:"Guruhdagi kelishmovchilikda qanday yo‘l tutasiz?",answers:["Tashkilotchi","Ijrochi","G‘oya beruvchi","Tahlilchi","Muloqotchi","Murosaga keltiruvchi"],category:"teamwork",weight:7},
{id:"q38",text:"Vazifa uchun muddat qisqa bo‘lsa nima qilasiz?",answers:["Vazifalarni bosqichlarga ajrataman","Darhol ishni boshlayman","Boshqalardan yordam so‘rayman","Eng oson qismini qilaman","Muddatni hisoblayman","Vaziyatga qarab o‘zgartiraman"],category:"organization",weight:7},
{id:"q39",text:"Qaysi turdagi natija sizni ko‘proq qoniqtiradi?",answers:["Qiziqish","Foyda keltirish","Rivojlanish","Barqarorlik","Ijodkorlik","Yaxshi daromad"],category:"motivation",weight:7},
{id:"q40",text:"Biror kasb haqida birinchi navbatda nimani bilishni xohlaysiz?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q41",text:"Amaliy mashg‘ulotda yangi asbob berilsa nima qilasiz?",answers:["Ichki tuzilishini o‘rganaman","Qanday ishlashini tekshiraman","Faqat foydalanaman","Qo‘llanmasini o‘qiyman","Tajriba qilib ko‘raman","Umuman qiziqmayman"],category:"technical",weight:7},
{id:"q42",text:"Kompyuter dasturi ishlamay qolsa nima qilasiz?",answers:["Muammoni qismlarga ajrataman","Sababini tekshiraman","Bir necha yechim solishtiraman","Yordam so‘rayman","Taxminiy yechimni sinayman","Keyinga qoldiraman"],category:"problem",weight:7},
{id:"q43",text:"Chizma yoki maket tayyorlashda nimaga ko‘proq e’tibor berasiz?",answers:["Rang va uyg‘unlikka","Aniqlik va o‘lchamga","Foydalanish qulayligiga","Tashqi ko‘rinishga","Texnik sxemaga","Minimalizmga"],category:"design",weight:7},
{id:"q44",text:"Biror ishni yolg‘iz bajarish va jamoada bajarishdan qaysi biri sizga mos?",answers:["Tashkilotchi","Ijrochi","G‘oya beruvchi","Tahlilchi","Muloqotchi","Murosaga keltiruvchi"],category:"teamwork",weight:7},
{id:"q45",text:"Odamlar oldida fikr bildirish siz uchun qanday?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q46",text:"Bir kunda bir necha xil vazifa berilsa qanday his qilasiz?",answers:["Turli vazifalar","Bir xil, tartibli ish","Loyihadan loyihaga o‘tish","Muammosi turlicha bo‘lgan ishlar","Odamlar bilan turli vaziyatlar","Aniq takroriy jarayon"],category:"variety",weight:7},
{id:"q47",text:"Kasb tanlashda o‘zingizga qaysi savolni berish muhim?",answers:["Qiziqishlarim","Kuchli fanlarim","Qobiliyatlarim","Xarakterim","Ishlash uslubim","Hali aniq bilmayman"],category:"selfknowledge",weight:10},
{id:"q48",text:"Kasbning kundalik ishini bilish uchun nima qilgan bo‘lardingiz?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q49",text:"Yangi qurilmani ko‘rsangiz nimalarni kuzatasiz?",answers:["Ichki tuzilishini o‘rganaman","Qanday ishlashini tekshiraman","Faqat foydalanaman","Qo‘llanmasini o‘qiyman","Tajriba qilib ko‘raman","Umuman qiziqmayman"],category:"technical",weight:7},
{id:"q50",text:"Qiyin masalada javob topilmasa qanday davom etasiz?",answers:["Muammoni qismlarga ajrataman","Sababini tekshiraman","Bir necha yechim solishtiraman","Yordam so‘rayman","Taxminiy yechimni sinayman","Keyinga qoldiraman"],category:"problem",weight:7},
{id:"q51",text:"O‘zingiz yasagan buyum ishlamasa nima qilasiz?",answers:["O‘zim bajarib ko‘raman","Ustozdan ko‘rsatma olaman","Asboblarni tekshiraman","Tayyor variantdan foydalanaman","Bir necha usul sinayman","Faqat nazariyani afzal ko‘raman"],category:"practical",weight:7},
{id:"q52",text:"Yangi dastur yoki platformani o‘rganish sizga qanday?",answers:["Darhol o‘rganib ko‘raman","Video yoki qo‘llanma izlayman","Boshqalar yordamidan foydalanaman","Faqat kerak bo‘lsa ishlataman","Yangi imkoniyatlarini sinayman","Qiziqmayman"],category:"technology",weight:7},
{id:"q53",text:"Ishingizni kimdir tanqid qilsa qanday qabul qilasiz?",answers:["Qayta urinib ko‘raman","Yordam so‘rayman","Boshqa usul sinayman","Vazifani keyinga qoldiraman","Faqat oson qismini qilaman","Natija chiqmaguncha davom etaman"],category:"persistence",weight:7},
{id:"q54",text:"Qaysi vazifa sizni uzoqroq vaqt qiziqtirib turadi?",answers:["Texnika va qurilmalar","Odamlar bilan ishlash","Ijod va dizayn","Tabiat va biologiya","Hisob-kitob va tahlil","Til va muloqot"],category:"interest",weight:7},
{id:"q55",text:"Maktabdagi qaysi topshiriqlarni bajarishda vaqt tez o‘tib ketadi?",answers:["Texnika va qurilmalar","Odamlar bilan ishlash","Ijod va dizayn","Tabiat va biologiya","Hisob-kitob va tahlil","Til va muloqot"],category:"interest",weight:7},
{id:"q56",text:"Qaysi faoliyatda o‘zingizni foydali his qilasiz?",answers:["Qiziqish","Foyda keltirish","Rivojlanish","Barqarorlik","Ijodkorlik","Yaxshi daromad"],category:"motivation",weight:7},
{id:"q57",text:"Biror qaror oldidan dalillarni qanday yig‘asiz?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q58",text:"Sizga tanish bo‘lmagan odam bilan ishlash kerak bo‘lsa?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q59",text:"Jamoada vazifalar taqsimlanganda qaysi rol sizga yaqin?",answers:["Tashkilotchi","Ijrochi","G‘oya beruvchi","Tahlilchi","Muloqotchi","Murosaga keltiruvchi"],category:"teamwork",weight:7},
{id:"q60",text:"Rejangiz buzilib qolsa nima qilasiz?",answers:["Vazifalarni bosqichlarga ajrataman","Darhol ishni boshlayman","Boshqalardan yordam so‘rayman","Eng oson qismini qilaman","Muddatni hisoblayman","Vaziyatga qarab o‘zgartiraman"],category:"organization",weight:7},
{id:"q61",text:"Bir xil usul ishlamasa qanday yo‘l tutasiz?",answers:["Muammoni qismlarga ajrataman","Sababini tekshiraman","Bir necha yechim solishtiraman","Yordam so‘rayman","Taxminiy yechimni sinayman","Keyinga qoldiraman"],category:"problem",weight:7},
{id:"q62",text:"Biror narsani boshqalardan farqli usulda bajarish haqida nima deysiz?",answers:["Bir nechta yangi variant o‘ylayman","Tayyor namunani takrorlayman","Boshqalardan g‘oya so‘rayman","Avvalgi usulni ishlataman","G‘oyani chizma qilib ko‘raman","Amalda sinab ko‘raman"],category:"creativity",weight:7},
{id:"q63",text:"Rang, shakl va ko‘rinish siz uchun ishda qanchalik muhim?",answers:["Rang va uyg‘unlikka","Aniqlik va o‘lchamga","Foydalanish qulayligiga","Tashqi ko‘rinishga","Texnik sxemaga","Minimalizmga"],category:"design",weight:7},
{id:"q64",text:"Tabiatdagi hodisalarni kuzatish sizga qiziqmi?",answers:["Inson organizmi","Kasalliklar va davolash","Laboratoriya tajribalari","Odamlarga yordam","Biologik tabiat","Bu soha qiziqtirmaydi"],category:"medicine",weight:7},
{id:"q65",text:"Odamlarga maslahat berish sizga yoqadimi?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q66",text:"Biror kasbning qiyin tomonlarini bilsangiz qaroringiz o‘zgaradimi?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q67",text:"Kasb tanlashda o‘z qobiliyatingizni qanday tekshirgan bo‘lardingiz?",answers:["Qiziqishlarim","Kuchli fanlarim","Qobiliyatlarim","Xarakterim","Ishlash uslubim","Hali aniq bilmayman"],category:"selfknowledge",weight:10},
{id:"q68",text:"Biror ishda mustaqil qaror qilish kerak bo‘lsa?",answers:["O‘zim qaror qilaman","Avval ma’lumot yig‘aman","Maslahat olib qaror qilaman","Ko‘rsatma bo‘lsa qulay","Jamoa bilan kelishaman","Vaziyatga qarayman"],category:"independence",weight:7},
{id:"q69",text:"Rahbaringiz sizga aniq ko‘rsatma bermasa nima qilasiz?",answers:["O‘zim qaror qilaman","Avval ma’lumot yig‘aman","Maslahat olib qaror qilaman","Ko‘rsatma bo‘lsa qulay","Jamoa bilan kelishaman","Vaziyatga qarayman"],category:"independence",weight:7},
{id:"q70",text:"Yangi loyiha boshlaganda nimadan boshlashni afzal ko‘rasiz?",answers:["Vazifalarni bosqichlarga ajrataman","Darhol ishni boshlayman","Boshqalardan yordam so‘rayman","Eng oson qismini qilaman","Muddatni hisoblayman","Vaziyatga qarab o‘zgartiraman"],category:"organization",weight:7},
{id:"q71",text:"Biror vazifada yordam so‘rashga munosabatingiz qanday?",answers:["Tashkilotchi","Ijrochi","G‘oya beruvchi","Tahlilchi","Muloqotchi","Murosaga keltiruvchi"],category:"teamwork",weight:7},
{id:"q72",text:"Murakkab narsani boshqalarga tushuntirish kerak bo‘lsa?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q73",text:"O‘zingizga yoqmaydigan, ammo muhim vazifa berilsa?",answers:["Qayta urinib ko‘raman","Yordam so‘rayman","Boshqa usul sinayman","Vazifani keyinga qoldiraman","Faqat oson qismini qilaman","Natija chiqmaguncha davom etaman"],category:"persistence",weight:7},
{id:"q74",text:"Kasb tanlashda do‘stlar ta’siridan qanday himoyalanasiz?",answers:["Do‘st fikrini faqat maslahat sifatida olaman","Do‘stim tanlaganini tanlayman","O‘zimning qiziqishimni tekshiraman","Kasb talablarini solishtiraman","Sinab ko‘rib keyin qaror qilaman","Do‘stlar fikri hal qiluvchi emas"],category:"error_peer",weight:10},
{id:"q75",text:"Ota-onangiz xohlagan kasb sizga mos kelmasa nima qilasiz?",answers:["Ota-onamni tinglayman, lekin moslikni tekshiraman","Ular tanlaganini tanlayman","O‘z qiziqishimni tushuntiraman","Kasb talablarini birga ko‘raman","Amaliy sinov qilib ko‘raman","Faqat o‘z xohishimga qarayman"],category:"error_parent",weight:10},
{id:"q76",text:"Yuqori maoshli, lekin qiziq bo‘lmagan kasb haqida fikringiz?",answers:["Maoshni boshqa omillar bilan birga ko‘raman","Faqat maosh muhim","Qiziqish va qobiliyatni tekshiraman","Kasbning kundalik ishini o‘rganaman","Rivojlanish imkonini solishtiraman","Prestijga qarab tanlayman"],category:"error_salary",weight:10},
{id:"q77",text:"Kasb tanlashdan oldin o‘zingiz haqingizda nimani aniqlaysiz?",answers:["Qiziqishlarim","Kuchli fanlarim","Qobiliyatlarim","Xarakterim","Ishlash uslubim","Hali aniq bilmayman"],category:"selfknowledge",weight:10},
{id:"q78",text:"Biror kasbni internetda izlaganda qaysi ma’lumotlar muhim?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q79",text:"Kasbning nomi emas, kundalik vazifalarini bilish nima uchun muhim?",answers:["Kasbni amalda sinab ko‘rish","Mutaxassis bilan suhbat","Kasb vazifalarini o‘rganish","O‘qish talablarini tekshirish","Mehnat bozorini ko‘rish","Faqat kasb nomiga qarash"],category:"career",weight:7},
{id:"q80",text:"Biror sohada ishlayotgan odam bilan suhbatlashish foydalimi?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q81",text:"Kelajakdagi ish joyingizni tasavvur qilganda nimaga qaraysiz?",answers:["Tinch kompyuterli xona","Laboratoriya","Ustaxona","Maktab yoki o‘quv muhiti","Ofis va odamlar bilan ishlash","Harakatdagi ish muhiti"],category:"environment",weight:7},
{id:"q82",text:"Ofis, ustaxona, laboratoriya yoki maktabdan qaysi muhit sizga yaqin?",answers:["Tinch kompyuterli xona","Laboratoriya","Ustaxona","Maktab yoki o‘quv muhiti","Ofis va odamlar bilan ishlash","Harakatdagi ish muhiti"],category:"environment",weight:7},
{id:"q83",text:"Ko‘p odam bilan ishlash va tinch muhitdan qaysi biri sizga qulay?",answers:["Tinch kompyuterli xona","Laboratoriya","Ustaxona","Maktab yoki o‘quv muhiti","Ofis va odamlar bilan ishlash","Harakatdagi ish muhiti"],category:"environment",weight:7},
{id:"q84",text:"Bir vaqtning o‘zida bir nechta odamning ehtiyojini hisobga olish kerak bo‘lsa?",answers:["Vazifalarni bosqichlarga ajrataman","Darhol ishni boshlayman","Boshqalardan yordam so‘rayman","Eng oson qismini qilaman","Muddatni hisoblayman","Vaziyatga qarab o‘zgartiraman"],category:"organization",weight:7},
{id:"q85",text:"Biror muammoni boshqa odamning nuqtayi nazaridan ko‘rish sizga osonmi?",answers:["Diqqat bilan tinglayman","O‘z fikrimni tushuntiraman","Savollar beraman","Suhbatdan qochaman","Murosali yechim izlayman","Faqat o‘z fikrimni aytaman"],category:"communication",weight:7},
{id:"q86",text:"Yangi mahsulot yoki xizmat yaratish g‘oyasi sizni qiziqtiradimi?",answers:["Bir nechta yangi variant o‘ylayman","Tayyor namunani takrorlayman","Boshqalardan g‘oya so‘rayman","Avvalgi usulni ishlataman","G‘oyani chizma qilib ko‘raman","Amalda sinab ko‘raman"],category:"creativity",weight:7},
{id:"q87",text:"Tayyor qoida asosida ishlash yoki o‘z usulingizni topishdan qaysi biri?",answers:["O‘zim qaror qilaman","Avval ma’lumot yig‘aman","Maslahat olib qaror qilaman","Ko‘rsatma bo‘lsa qulay","Jamoa bilan kelishaman","Vaziyatga qarayman"],category:"independence",weight:7},
{id:"q88",text:"Hisob-kitobdagi xatoni topish sizga qanday tuyuladi?",answers:["Raqam va hisob-kitob","Sabab-oqibat","Qoidalar","Jadval va ma’lumotlar","Tajriba natijalari","Mantiqiy boshqotirmalar"],category:"logic",weight:7},
{id:"q89",text:"Matn, jadval yoki rasm bilan ishlashdan qaysi biri sizga yaqin?",answers:["Rang va uyg‘unlikka","Aniqlik va o‘lchamga","Foydalanish qulayligiga","Tashqi ko‘rinishga","Texnik sxemaga","Minimalizmga"],category:"design",weight:7},
{id:"q90",text:"Inson organizmi va sog‘liq haqida o‘rganish sizga qiziqmi?",answers:["Inson organizmi","Kasalliklar va davolash","Laboratoriya tajribalari","Odamlarga yordam","Biologik tabiat","Bu soha qiziqtirmaydi"],category:"medicine",weight:7},
{id:"q91",text:"Laboratoriya tajribasida natija kutilgandek chiqmasa?",answers:["Muammoni qismlarga ajrataman","Sababini tekshiraman","Bir necha yechim solishtiraman","Yordam so‘rayman","Taxminiy yechimni sinayman","Keyinga qoldiraman"],category:"problem",weight:7},
{id:"q92",text:"Qurilmani qismlarga ajratib o‘rganishga munosabatingiz?",answers:["Ichki tuzilishini o‘rganaman","Qanday ishlashini tekshiraman","Faqat foydalanaman","Qo‘llanmasini o‘qiyman","Tajriba qilib ko‘raman","Umuman qiziqmayman"],category:"technical",weight:7},
{id:"q93",text:"Biror narsani qo‘l bilan yasash va uni bezashdan qaysi biri sizga yaqin?",answers:["O‘zim bajarib ko‘raman","Ustozdan ko‘rsatma olaman","Asboblarni tekshiraman","Tayyor variantdan foydalanaman","Bir necha usul sinayman","Faqat nazariyani afzal ko‘raman"],category:"practical",weight:7},
{id:"q94",text:"Biror vazifada natijani oldindan taxmin qilishni yoqtirasizmi?",answers:["Raqam va hisob-kitob","Sabab-oqibat","Qoidalar","Jadval va ma’lumotlar","Tajriba natijalari","Mantiqiy boshqotirmalar"],category:"logic",weight:7},
{id:"q95",text:"Biror kasbni tanlashda ish va shaxsiy hayot muvozanati muhimmi?",answers:["Qiziqish","Foyda keltirish","Rivojlanish","Barqarorlik","Ijodkorlik","Yaxshi daromad"],category:"motivation",weight:7},
{id:"q96",text:"Kasb tanlashda qaysi xato eng xavfli deb o‘ylaysiz?",answers:["Qiziqishlarim","Kuchli fanlarim","Qobiliyatlarim","Xarakterim","Ishlash uslubim","Hali aniq bilmayman"],category:"selfknowledge",weight:10},
{id:"q97",text:"Kasb haqida qarama-qarshi ikki fikr topsangiz nima qilasiz?",answers:["Rasmiy manbalarni tekshiraman","Mutaxassisdan so‘rayman","Bir nechta manbani solishtiraman","Faqat tanishim fikriga ishonaman","Reklamadagi ma’lumotni olaman","Umuman tekshirmayman"],category:"information",weight:10},
{id:"q98",text:"Qaysi ishda kun davomida o‘zgarib turadigan vazifalar sizga yoqadi?",answers:["Turli vazifalar","Bir xil, tartibli ish","Loyihadan loyihaga o‘tish","Muammosi turlicha bo‘lgan ishlar","Odamlar bilan turli vaziyatlar","Aniq takroriy jarayon"],category:"variety",weight:7},
{id:"q99",text:"Biror loyihani oxirigacha yetkazishda sizga nima yordam beradi?",answers:["Qayta urinib ko‘raman","Yordam so‘rayman","Boshqa usul sinayman","Vazifani keyinga qoldiraman","Faqat oson qismini qilaman","Natija chiqmaguncha davom etaman"],category:"persistence",weight:7},
{id:"q100",text:"Kasb tanlashdan oldin kichik sinov yoki amaliyot qilib ko‘rish haqida nima deysiz?",answers:["Kasbni amalda sinab ko‘rish","Mutaxassis bilan suhbat","Kasb vazifalarini o‘rganish","O‘qish talablarini tekshirish","Mehnat bozorini ko‘rish","Faqat kasb nomiga qarash"],category:"career",weight:7}
{id:"q101",text:"Hozir nechanchi sinfda o‘qiyapsiz?",answers:["8-sinf","9-sinf","10-sinf","11-sinf","Kollej/litsey","Boshqa"],category:"education",weight:5},
{id:"q102",text:"Yoshingiz haqida aytsangiz, kasb rejangiz qaysi bosqichda?",answers:["13–14 yosh","15 yosh","16 yosh","17 yosh","18 yosh yoki katta","Aniq aytishni istamayman"],category:"age",weight:5},
];

const PROFESSIONS=[
{id:"programmer",name:"Dasturchi",requirements:{logic:90,problem:90,technology:85,independence:80,creativity:65,communication:50},evidence:["interest","logic","problem","technology","independence","motivation"]},
{id:"engineer",name:"Muhandis",requirements:{logic:85,problem:90,technology:95,practical:90,creativity:65,communication:55},evidence:["interest","problem","technology","practical","technical","design"]},
{id:"designer",name:"Dizayner",requirements:{creativity:90,technology:65,practical:50,communication:60},evidence:["interest","creativity","technology","design","practical"]},
{id:"teacher",name:"O‘qituvchi",requirements:{communication:90,teamwork:85,organization:80,logic:65,creativity:70},evidence:["communication","teamwork","organization","creativity","logic"]},
{id:"doctor",name:"Shifokor",requirements:{medicine:90,communication:80,problem:80,organization:75},evidence:["medicine","communication","problem","organization","interest"]},
{id:"lawyer",name:"Huquqshunos",requirements:{logic:80,communication:85,organization:80,problem:80},evidence:["problem","communication","organization","logic","motivation"]},
{id:"economist",name:"Iqtisodchi",requirements:{logic:85,organization:85,problem:75,communication:65},evidence:["logic","problem","organization","motivation","communication"]},
{id:"psychologist",name:"Psixolog",requirements:{communication:95,teamwork:80,creativity:65,problem:75},evidence:["communication","teamwork","problem","creativity","interest"]},
{id:"architect",name:"Arxitektor",requirements:{creativity:85,logic:80,design:90,practical:65},evidence:["design","creativity","technical","practical","interest"]},
{id:"technologist",name:"Texnolog",requirements:{technology:85,practical:85,logic:80,organization:75},evidence:["technology","practical","technical","problem","organization"]}
];